version: "3.3"

networks:
  traefik:
    external: true

services:
  web:
    image: nginx:alpine
    volumes:
      - .:/www/
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

