version: "3.3"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/ssl/fullchain.pem
      - ./privKey.pem:/ssl/privKey.pem
    ports:
      - "80:80"
      - "443:443"
