version: "3.3"

networks:
  traefik:
    external: true

services:
  api:
    env_file:
      - .env
    container_name: api
    depends_on:
      - db
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    restart: always
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host=0.0.0.0",
        "--port=${API_PORT}",
      ]
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.services.api.loadbalancer.server.port=${API_PORT}"
      - "traefik.http.routers.api.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

  db:
    container_name: db
    image: mariadb:10.9.2-jammy
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - traefik

  adminer:
    container_name: adminer
    restart: always
    depends_on:
      - db
    image: adminer:4.8.1-standalone
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.routers.adminer.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"


