version: "3.3"

services:
  api:
    env_file:
      - .env
    container_name: api
    depends_on:
      - db
    build: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app
    working_dir: /app
    restart: always
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host=0.0.0.0",
        "--port=${API_PORT}",
      ]

  db:
    container_name: db
    image: mariadb:10.9.2-jammy
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  adminer:
    env_file:
      - .env
    container_name: adminer
    restart: always
    depends_on:
      - db
    image: adminer:4.8.1-standalone
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: db


